name: mini_tea

packages:
  - packages/**

ignore:
  - packages/**/example

scripts:
  analyze:
    exec: flutter analyze .
  test:
    run: flutter test
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test
