name: mini_tea_test
description: –
version: 0.1.0
repository: https://github.com/Vorkytaka/mini_tea/packages/mini_tea_test

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.0.0
  mini_tea: ^0.0.1
  test: ^1.16.0

dev_dependencies:
  lints: ^4.0.0
