name: mini_tea
description: The Elm Architecture for Dart and Flutter applications.
version: 0.1.0

repository: https://github.com/Vorkytaka/mini_tea/tree/master/packages/mini_tea
issue_tracker: https://github.com/Vorkytaka/mini_tea/issues
homepage: https://github.com/Vorkytaka/mini_tea
topics:
  - state-management
  - architecture
  - unidirectional-data-flow
  - mvi

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.0.0
  rxdart: '>=0.27.0 <1.0.0'

dev_dependencies:
  lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.24.0