name: mini_tea
description: –
version: 0.0.1
repository: https://github.com/Vorkytaka/mini_tea/packages/mini_tea

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.0.0
  rxdart: '>=0.27.0 <1.0.0'

dev_dependencies:
  lints: ^4.0.0
  mocktail: ^1.0.4
  test: ^1.24.0